export * from './account-type.repository.interface';
export * from './account.repository.interface';
export * from './customer.repository.interface';
export * from './deposit.repository.interface';
export * from './disableable.repository.interface';
export * from './document-type.repository.interface';
export * from './IGeneral.interface';
export * from './nameable.repository.interface';
export * from './transfer.repository.interface';
